<?php
function reposi_has_role() {
  global $user;
  $roles = array('authenticated user','administrator','anonymous user');
  foreach ($roles as $role) {
    if (in_array($role, $user->roles)) {
      return TRUE;
    }
  }
  return FALSE;
}

function _reposi_user_role_administrator() { 
  global $user;
  $roles = array('administrator');
  foreach ($roles as $role) {
    if (in_array($role, $user->roles)) {
      return TRUE;
    }
  }
  return FALSE;
}
?>
